apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
  labels:
    app: strapi
spec:
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      restartPolicy: Always
      volumes:
      - name: strapi-uploads-pv
        persistentVolumeClaim:
          claimName: strapi-uploads-pvc
      - name: strapi-data-pv
        persistentVolumeClaim:
          claimName: strapi-data-pvc
      - name: strapi-components-pv
        persistentVolumeClaim:
          claimName: strapi-components-pvc
      - name: strapi-extensions-pv
        persistentVolumeClaim:
          claimName: strapi-extensions-pvc
      containers:
        - name: strapi
          image: registry.gitlab.com/farcasmihai91/starter/static-cms:05d9285d
          imagePullPolicy: Always
          volumeMounts:
            - name: strapi-uploads-pv
              mountPath: /srv/app/public/uploads
            - name: strapi-data-pv
              mountPath: /srv/app/src/api
            - name: strapi-components-pv
              mountPath: /srv/app/src/components
            - name: strapi-extensions-pv
              mountPath: /srv/app/src/extensions
          resources:
            limits:
              cpu: "500m"
              memory: "800Mi"
          env:
            - name: DATABASE_CLIENT
              value: postgres
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: strapi-db-pguser-strapi
                  key: dbname
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: strapi-db-pguser-strapi
                  key: host
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: strapi-db-pguser-strapi
                  key: port
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: strapi-db-pguser-strapi
                  key: user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: strapi-db-pguser-strapi
                  key: password
