apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: strapi-data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeName: strapi-pv
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi